---
title: "p8105_hw2_LC4052"
Author: "Linqi Chu"
output: github_document
date: "2025-09-28"
---

```{r}
library(tidyverse)
library(dplyr)

```


# Problem 1

## Clean the data in pols-month.csv

```{r}
pols_month = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv",
           na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(mon, c("year", "month","day")) |>
  mutate(
    month = month.name[as.integer(month)],
    president = ifelse(prez_gop == 1, "gop", "dem")
  )|>
  select(-prez_dem, -prez_gop, -day)

```


## Clean the data in snp.csv

```{r}
snp = 
  read_csv("./fivethirtyeight_datasets/snp.csv",
           na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(date, c("month", "day","year")) |>
  mutate(
    month = month.name[as.integer(month)],
    year = as.integer(year),
    year = ifelse(year < 50,
                 2000 + year,
                 1900 + year)) |>
  select(-day) |>
  relocate(year, month, .before = everything()) |> 
  arrange(year, month)


```

Third, tidy the unemployment data so that it can be merged with the previous datasets. This process will involve switching from “wide” to “long” format; ensuring that key variables have the same name; and ensuring that key variables take the same values.


```{r}
  arrange()








```




```{r}










```


