p8105_hw2_LC4052
================
2025-09-28

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.2
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
library(readxl)
```

# Problem 1

## Clean the data in pols-month.csv

``` r
pols_month = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv",
           na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(mon, c("year", "month","day")) |>
  mutate(
    month = month.name[as.integer(month)],
    president = ifelse(prez_gop == 1, "gop", "dem")
  )|>
  select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Clean the data in snp.csv

``` r
snp_df = 
  read_csv("./fivethirtyeight_datasets/snp.csv",
           na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(date, c("month", "day","year")) |>
  mutate(
    month = month.name[as.integer(month)],
    year = as.integer(year),
    year = ifelse(year < 50,
                 2000 + year,
                 1900 + year),
    year = as.character(year)) |>
  select(-day) |>
  relocate(year, month, .before = everything()) |> 
  arrange(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Tidy the unemployment data

``` r
unemployment_df = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv",
           na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "unemployment(%)") |>
  mutate(
    month = factor(month, 
                      levels = c("jan","feb","mar","apr","may","jun",
                                 "jul","aug","sep","oct","nov","dec"),
                      labels = month.name),
    year = as.character(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Join the datasets by merging snp into pols, and merging unemployment into the result

``` r
pols_df = 
  left_join(pols_month, snp_df, by = c("year","month")) |>
  left_join(unemployment_df, by = c("year","month"))
```

## Description of datasets

``` r
names(pols_month)
```

    ## [1] "year"      "month"     "gov_gop"   "sen_gop"   "rep_gop"   "gov_dem"  
    ## [7] "sen_dem"   "rep_dem"   "president"

``` r
names(snp_df)
```

    ## [1] "year"  "month" "close"

``` r
names(unemployment_df)
```

    ## [1] "year"            "month"           "unemployment(%)"

``` r
names(pols_df)
```

    ##  [1] "year"            "month"           "gov_gop"         "sen_gop"        
    ##  [5] "rep_gop"         "gov_dem"         "sen_dem"         "rep_dem"        
    ##  [9] "president"       "close"           "unemployment(%)"

Pols-month contains variables:“year”, “month”, “gov_gop”, “sen_gop”,
“rep_gop”, “gov_dem”, “sen_dem”, “rep_dem” and “president”. Snp_df
contains variables: “year”, “month” and “close”. Unemployment_df
contains variables: “year”, “month” and “unemployment(%)”.

The resulting dataset spans from 1947 to 2015 and contains 822
observations, each with 11 features. It contains variables: “year”,
“month”, “gov_gop”, “sen_gop”, “rep_gop”, “gov_dem”, “sen_dem”,
“rep_dem”, “president”, “close” and “unemployment(%)”.

# Problem 2

## Clean the Mr. Trash Wheel sheet

``` r
mrtrash_df = 
  read_excel("./trash_collection_data/202509 Trash Wheel Collection Data.xlsx",
             sheet = "Mr. Trash Wheel",
             skip = 1,
             na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  select(-c(15, 16)) |>
  filter(!is.na(dumpster) & !is.na(weight_tons)) |>
  mutate(sports_balls = as.integer(round(sports_balls))) |>
  mutate(trash_wheel = "Mr. Trash Wheel") |>
  mutate(year = as.integer(year))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

## Clean the Professor Trash Wheel dataset

``` r
protrash_df = 
  read_excel("./trash_collection_data/202509 Trash Wheel Collection Data.xlsx",
             sheet = "Professor Trash Wheel",
             skip = 1,
             na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster) & !is.na(weight_tons)) |>
  mutate(trash_wheel = "Professor Trash Wheel") |>
  mutate(year = as.integer(year))
```

## Clean the Gwynnda Trash Wheel dataset

``` r
gwytrash_df = 
  read_excel("./trash_collection_data/202509 Trash Wheel Collection Data.xlsx",
             sheet = "Gwynns Falls Trash Wheel",
             skip = 1,
             na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster) & !is.na(weight_tons)) |>
  mutate(trash_wheel = "Gwynnda Trash Wheel") |>
  mutate(year = as.integer(year))
```

# Combine the three datasets

``` r
trash_data <- bind_rows(mrtrash_df, protrash_df, gwytrash_df)
```

The resulting data has 1188 observations, each with 15 variables. The
key variables are: dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered,
trash_wheel.

The total weight of trash collected by Professor Trash Wheel is 282.26.
The total number of cigarette butts collected by Gwynnda in June of 2022
is 1.04482^{6}.

# Problem 3

## Create a single, well-organized dataset

### Clean the zip_codes file

``` r
zipcodes_df = 
  read_csv("./zillow_data/Zip Codes.csv",
             na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  select(county,zip_code, everything(), -file_date)
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): County, File Date, Neighborhood
    ## dbl (4): State FIPS, County Code, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
names(zipcodes_df)
```

    ## [1] "county"       "zip_code"     "state_fips"   "county_code"  "county_fips" 
    ## [6] "neighborhood"

### Clean the zip_zori file

``` r
zori_df = 
  read_csv("./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv",
             na = c("NA", ".", "")) |>
  pivot_longer(
    cols = 10 : 125,
    names_to = "file_date", 
    values_to = "rent_price") |>
    mutate(file_date = as.character(file_date)) |>
  rename(county = CountyName, zip_code = RegionName) |>                       
  mutate(county = sub(" County$", "", county)) |> 
  arrange(zip_code) |>
  select(county,zip_code,file_date, rent_price, everything())
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
names(zori_df)
```

    ##  [1] "county"     "zip_code"   "file_date"  "rent_price" "RegionID"  
    ##  [6] "SizeRank"   "RegionType" "StateName"  "State"      "City"      
    ## [11] "Metro"

### Combine the two datasets

``` r
combined_data = 
  full_join(zipcodes_df, zori_df, by = c("county","zip_code")) |>
  select(county,zip_code,file_date, rent_price, neighborhood, everything())
```

## Descriptions

The resulting dataset contains information from two zillow datasets
(`zipcodes_df` and `zori_df`) with 17458 observations and 15 variables.
Each observation has its identical variables (`county`, `zip_code`,
`file_date`), and some other variables such as `rent_price` and
`neighborhood`.

### unique zip codes

``` r
combined_data |> 
  distinct(zip_code) |> 
  nrow()
```

    ## [1] 320

There are 320 unique ZIP codes.

### unique neighborhoods

``` r
combined_data |> 
  distinct(neighborhood) |> 
  nrow()
```

    ## [1] 43

There are 43 unique neighborhoods.

### unique zip codes in `zip_codes`

``` r
missing_part = 
  zipcodes_df |> 
  anti_join(zori_df, by = "zip_code") |> 
  distinct(zip_code)

print(missing_part)
```

    ## # A tibble: 171 × 1
    ##    zip_code
    ##       <dbl>
    ##  1    10464
    ##  2    10474
    ##  3    10475
    ##  4    10499
    ##  5    10550
    ##  6    10704
    ##  7    10705
    ##  8    10803
    ##  9    11202
    ## 10    11224
    ## # ℹ 161 more rows

The above are the ZIP codes appear in the ZIP code dataset but not in
the Zillow Rental Price dataset.

### Using a few illustrative examples discuss why these ZIP codes might be excluded from the Zillow dataset.

Possible reasons include: (1) These ZIP codes are primarily
commercial,institutional or parks rather than residential. (2) The
number of rental units is too small for Zillow to reliably estimate rent
prices. (3) The ZIP code is new or unique-purpose (assigned to an
organization or facility).

### Comparision table

``` r
subset = combined_data |>
  filter(file_date %in% c("2020-01-31", "2021-01-31"))
```

``` r
comparison = subset |>
  select(zip_code, file_date, rent_price, county, neighborhood) |>
  pivot_wider(
    names_from = file_date, 
    values_from = rent_price,
    names_prefix = "price_"
  ) |>
  mutate(price_change = `price_2021-01-31` - `price_2020-01-31`)
```

``` r
top10_drop = comparison |>
  filter(price_change < 0) |>
  arrange(price_change) |>
  drop_na(price_change) |>
  select(
    borough = county,
    zip_code,
    neighborhood,
    price_drop = price_change
  )|>
   head(10)

print(top10_drop)
```

    ## # A tibble: 10 × 4
    ##    borough  zip_code neighborhood                  price_drop
    ##    <chr>       <dbl> <chr>                              <dbl>
    ##  1 New York    10007 Lower Manhattan                    -913.
    ##  2 New York    10069 <NA>                               -748.
    ##  3 New York    10009 Lower East Side                    -714.
    ##  4 New York    10016 Gramercy Park and Murray Hill      -712.
    ##  5 New York    10001 Chelsea and Clinton                -710.
    ##  6 New York    10002 Lower East Side                    -710.
    ##  7 New York    10004 Lower Manhattan                    -706.
    ##  8 New York    10038 Lower Manhattan                    -698.
    ##  9 New York    10012 Greenwich Village and Soho         -686.
    ## 10 New York    10010 Gramercy Park and Murray Hill      -685.

The result shows that rent price in Manhattan county dropped the most
during the COVID-19 pandemic, with decreases ranging from approximately
685 dollars to 913 dollars. Particularly affected were premium
neighborhoods including Lower Manhattan, Lower East Side, Chelsea and
Clinton, and Gramercy Park, reflecting a broader trend of urban
out-migration which may be caused by remote work opportunities.
